### ISSUE TITLE
Syntax validation rejects valid input

### ISSUE THREAD

**Issue by LeopoldArkham** [bungcip/better-toml#5] opened 2017-09-20 12:23 UTC
Hey,

The extension doesn't seem to know that all string and array types are considered homogeneous, [as per the standard](https://github.com/toml-lang/toml#array).

Paste the 'arr1' through 'arr5' lines from the link above to reproduce.

Thanks for the useful extension!
BR

**Comment by bungcip** [comment] 2017-09-21 18:27
Hi @LeopoldArkham, thanks for your report.
I think this problem can be fixed with just upgrading `node-toml` package version.

**Comment by bungcip** [comment] 2017-09-21 19:49
after futher investigation, I think the problem is not `node-toml` package because the input can be parsed. Syntax hightlighting in `toml.tmLanguage` is the culprit.

**Comment by bungcip** [comment] 2017-09-21 21:29
Ok. I already push the fix in new branch `0.3`. just need to release this in weekends.

![new_toml](https://user-images.githubusercontent.com/72723/30719608-5eccbd86-9f4e-11e7-8dbc-89dcca011592.png)

**Comment by bungcip** [comment] 2017-09-22 05:34
version `0.3` already released so I will close this issue.

**Closed as completed by bungcip** 2017-09-22 05:34 UTC

**Comment by LeopoldArkham** [comment] 2017-09-22 07:41
Awesome!
